apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dotnet
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: spring-sensors
    apps.tanzu.vmware.com/scanning: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1684940211122147494"
    kapp.k14s.io/association: v1.324bc5f838fcc121291ca230d9b1c970
    app.kubernetes.io/component: run
    carto.run/workload-name: dotnet
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kapp.k14s.io/identity: v1;workloads/carto.run/Workload/dotnet;carto.run/v1alpha1
        kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"app.kubernetes.io/part-of":"spring-sensors","apps.tanzu.vmware.com/scanning":"true","apps.tanzu.vmware.com/workload-type":"web","kapp.k14s.io/app":"1684940211122147494","kapp.k14s.io/association":"v1.324bc5f838fcc121291ca230d9b1c970"},"name":"dotnet","namespace":"workloads"},"spec":{"build":{"env":[{"name":"BP_JVM_VERSION","value":"17"}]},"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}},{"name":"gitops_server_address","value":"https://github.com/"},{"name":"gitops_repository_owner","value":"cpage-pivotal"},{"name":"gitops_repository_name","value":"tap-gitops"}],"source":{"git":{"ref":{"branch":"main"},"subPath":"dotnet-core/aspnet","url":"https://github.com/cpage-pivotal/aspnet"}}}}'
        kapp.k14s.io/original-diff-md5: b517005b6f6db4769fb95ef8bca74b6a
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: spring-sensors
        apps.tanzu.vmware.com/scanning: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: dotnet
        kapp.k14s.io/app: "1684940211122147494"
        kapp.k14s.io/association: v1.324bc5f838fcc121291ca230d9b1c970
    spec:
      containers:
      - image: gcr.io/fe-cpage/tap/supply-chain/dotnet-workloads@sha256:4efbde4fe075eabf8f29ed17064c2cee6e68aa39e5b753ac5e4f371493ddefe7
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

