apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanzu-java-web-app-edge
spec:
  selector:
    matchLabels:
      app: tanzu-java-web-app-edge
  template:
    metadata:
      labels:
        app: tanzu-java-web-app-edge
    spec:
      containers:
      - name: pos-txn-monitor-dotnet
        image: gcr.io/fe-cpage/apps/tanzu-java-web-app-edge-default@sha256:1745b72e9f6a3c7745cf6598b19c13352f24f02e197d33d20eea5824deb09950
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tanzu-java-web-app-edge
  labels:
    app: tanzu-java-web-app-edge
spec:
  ports:
  - port: 80
    targetPort: http
  selector:
    app: tanzu-java-web-app-edge

