apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: spring-sensors-tanzu-developer-connect-w01-s004
  labels:
    app.kubernetes.io/part-of: spring-sensors
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1652452801393659671"
    kapp.k14s.io/association: v1.da12a9630afe3f6edf36e503c78fe9fb
    app.kubernetes.io/component: run
    carto.run/workload-name: spring-sensors-tanzu-developer-connect-w01-s004
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        boot.spring.io/actuator: http://:8081/actuator
        boot.spring.io/version: 2.5.6
        conventions.apps.tanzu.vmware.com/applied-conventions: |-
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          spring-boot-convention/spring-boot-actuator
          spring-boot-convention/service-intent-mysql
          appliveview-sample/app-live-view-connector
          appliveview-sample/app-live-view-appflavours
          appliveview-sample/app-live-view-systemproperties
        developer.conventions/target-containers: workload
        kapp.k14s.io/identity: v1;default/carto.run/Workload/spring-sensors-tanzu-developer-connect-w01-s004;carto.run/v1alpha1
        kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"app.kubernetes.io/part-of":"spring-sensors","apps.tanzu.vmware.com/workload-type":"web","kapp.k14s.io/app":"1652452801393659671","kapp.k14s.io/association":"v1.da12a9630afe3f6edf36e503c78fe9fb"},"name":"spring-sensors-tanzu-developer-connect-w01-s004","namespace":"default"},"spec":{"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}},{"name":"gitops_repository","value":"ssh://git@github.com/cpage-pivotal/tap-gitops"},{"name":"gitops_branch","value":"spring-sensors-tanzu-developer-connect-w01-s004"}],"source":{"git":{"ref":{"branch":"main"},"url":"https://gitea.tap.corby.cc/gitea_admin/tanzu-developer-connect-w01-s004-1654185827.git"}}}}'
        kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
        services.conventions.apps.tanzu.vmware.com/mysql: mysql-connector-java/8.0.27
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: spring-sensors
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: spring-sensors-tanzu-developer-connect-w01-s004
        conventions.apps.tanzu.vmware.com/framework: spring-boot
        kapp.k14s.io/app: "1652452801393659671"
        kapp.k14s.io/association: v1.da12a9630afe3f6edf36e503c78fe9fb
        services.conventions.apps.tanzu.vmware.com/mysql: workload
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.actuator.port: "8081"
        tanzu.app.live.view.application.flavours: spring-boot
        tanzu.app.live.view.application.name: spring-sensors
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.endpoint.health.show-details=always -Dmanagement.endpoints.web.base-path="/actuator" -Dmanagement.endpoints.web.exposure.include=* -Dmanagement.health.probes.enabled="true" -Dmanagement.server.port="8081" -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: harbor.contour.e2e.corby.cc/tap/supply-chain/spring-sensors-tanzu-developer-connect-w01-s004-default@sha256:4e5dc20565be52cc09ad4a1de187b401cad190f48b31c531b7801c7069a206c2
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

