apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: spring-sensors-test-db
  annotations:
    kapp.k14s.io/identity: v1;workloads/carto.run/Workload/spring-sensors-test;carto.run/v1alpha1
    autoscaling.knative.dev/minScale: "1"
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: spring-sensors
    apps.tanzu.vmware.com/scanning: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1683326647567770910"
    kapp.k14s.io/association: v1.6cb9f43f534bf663a9c47642e3739376
    app.kubernetes.io/component: run
    carto.run/workload-name: spring-sensors-test
spec:
  name: db
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ClassClaim
    name: sensors-mysql
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: spring-sensors-test

