apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: alcon-sensors-db
  annotations:
    kapp.k14s.io/identity: v1;default/carto.run/Workload/alcon-sensors;carto.run/v1alpha1
    kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"app.kubernetes.io/part-of":"spring-sensors","apps.tanzu.vmware.com/scanning":"true","apps.tanzu.vmware.com/workload-type":"web","kapp.k14s.io/app":"1663618906979073688","kapp.k14s.io/association":"v1.81545dc4c27dd4289548417c3de6fb56"},"name":"alcon-sensors","namespace":"default"},"spec":{"build":{"env":[{"name":"BP_JVM_VERSION","value":"17"}]},"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"2"}},{"name":"gitops_repository","value":"ssh://git@github.com/cpage-pivotal/tap-gitops"},{"name":"gitops_branch","value":"alcon-sensors"}],"serviceClaims":[{"name":"db","ref":{"apiVersion":"with.sql.tanzu.vmware.com/v1","kind":"MySQL","name":"sensors-mysql"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://gitea.tap.corby.cc/gitea_admin/alcon-sensors.git"}}}}'
    kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
    autoscaling.knative.dev/minScale: "2"
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: spring-sensors
    apps.tanzu.vmware.com/scanning: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1663618906979073688"
    kapp.k14s.io/association: v1.81545dc4c27dd4289548417c3de6fb56
    app.kubernetes.io/component: run
    carto.run/workload-name: alcon-sensors
spec:
  name: db
  service:
    apiVersion: with.sql.tanzu.vmware.com/v1
    kind: MySQL
    name: sensors-mysql
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: alcon-sensors

